[tool.poetry]
name = "tradingstation"
version = "0.1.0"
description = ""
authors = ["ghiaccionove <ant.cito@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.2"
ccxt = "^4.3.42"
ta-lib = {path = "libs/TA_Lib-0.4.24-cp310-cp310-win_amd64.whl"}
numpy = "^1.26.4"
prompt-toolkit = "^3.0.51"
requests = "^2.34.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
