class Signal:
    BUY = 'BUY'
    SELL = 'SELL'
    HOLD = 'HOLD'
    OVERBOUGHT = 'OVERBOUGHT'
    OVERSOLD = 'OVERSOLD'
    UP = 'UP'
    DOWN = 'DOWN'
    HIGH_VOLATILITY = 'HIGH_VOLATILITY'
    LOW_VOLATILITY = 'LOW_VOLATILITY'

